### ISSUE TITLE
Use 16 bit binary primary key leads to duplicate entry error

### ISSUE THREAD

**Issue by elovin** [MechJosh0/typeorm-buffer-example#1]
@MechJosh0 Thank you for the example, I try to get this to work with a 16bit binary/varbinary primary key uuid but when I use the save logic from your example I get this error:

`QueryFailedError: ER_DUP_ENTRY: Duplicate entry '\xD8mU1b\xF0J\xFD\xAA\xDC\4\xA4\xEE\xECa' for key 'PRIMARY'`

User primary column:

```
    @PrimaryColumn({type: "binary",name: "id", length: 16} )
    id!: Buffer|string;
```

Your code to update the entity. 

```
        await getConnection().transaction(async transactionalEntityManager => {
            const currentUser = await this.usersRepository.findOne({ id: uuidBuffer.toBuffer(id as string) });

            this.usersRepository.merge(currentUser,user);

            await transactionalEntityManager.save(currentUser);
        });
```

This works however just fine:
```

        await getConnection().transaction(async transactionalEntityManager => {
            const currentUser = await this.usersRepository.findOne({ id: uuidBuffer.toBuffer(id as string) });

            this.usersRepository.merge(currentUser,user);

            await transactionalEntityManager.update(User,{ id: uuidBuffer.toBuffer(id as string) }, user);
        });
```

**Comment by MechJosh0** [comment]
Are you trying to save the ids as uuids? You'll want to change the primary column type to string, it'd still set as binary from your example there.

**Comment by elovin** [comment]
No I save them as binary but convert the buffer to string for the frontend, before insert/update I convert it to a Buffer again.

I convert the uuid to a 16 bit buffer so I can save it to a 16 bit primary binary key.

`Buffer.from(id.replace(/-/g,''), 'hex')`

This works for save when the record does not exist but I can't use save to update the entity because it throws a dublicate key error.


**Update:**

Okay I used utf-8 encoding and now it works but now I need 36 bits as opposed to 16, but at least it works now thanks for your help :)

**Comment by elovin** [comment]
My intention was to create a bug report for typeorm, so I forked your example and modified it to work with 16 bit binary primary columns and hex encoded uuids, **this however worked just fine, so the issue was apparently with my setup**, thanks again for providing this example :)
